version: "2"
services:
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5.7
        ports: 
            - "3307:3307"
        environment:
            MYSQL_DATABASE: myDB
            MYSQL_USER: maarten
            MYSQL_PASSWORD: R1234-56
            MYSQL_ROOT_PASSWORD: R1234-56
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8050:80
        environment:
            MYSQL_USER: maarten
            MYSQL_PASSWORD: R1234-56
            MYSQL_ROOT_PASSWORD: R1234-56
    portainer:
        image: portainer/portainer
        command: -H unix:///var/run/docker.sock
        restart: always
        ports:
            - 9000:9000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
volumes:
    persistent:
    portainer_data:
